services:
  - type: web
    name: medinote-backend
    env: python
    buildCommand: ./render-build.sh
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0

